### ISSUE TITLE
Packer stuck on Creating hard drive step

### ISSUE THREAD

**Issue by tensor5g** [aoktox/aws-pfsense-ami#4]
After installing the exact same versions as described in the readme, I encountered this problem while running packer build packer.json

Once it reaches step "==> virtualbox-iso: Creating hard drive..." it does not progress. I let it run overnight to no avail. It seems when it first starts running, there is a disk defrag process in task manager, but eventually that goes away and there is seemingly nothing happening. If I cancel with control+c, I get this error:

> Cancelling build after receiving interrupt
==> virtualbox-iso: Error finding port: port 3389 cannot be opened: listen tcp 127.0.0.1:3389: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
==> virtualbox-iso: Deregistering and deleting VM...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Error finding port: port 3389 cannot be opened: listen tcp 127.0.0.1:3389: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
Cleanly cancelled builds after being interrupted.

Packer was run with admin rights.

**Comment by aoktox** [comment]
> access a socket in a way forbidden by its access permissions

Hi, @tensor5g sorry for the late reply, perhaps you need to check with your security or firewall setting, did you use windows OS?

**Comment by tensor5g** [comment]
I did this from a Windows 10 Sandbox which has UAC and Defender disabled by default. Perhaps this just won't work from a Sandbox for other reasons. I switched from AWS to Vultr (which lets you install via iso) so I personally don't need this method anymore. Thanks for the response, though!

**Comment by aoktox** [comment]
sure, I'm closing this issue then 🙇
